# Generated by Django 6.0.4 on 2026-05-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plano', models.CharField(max_length=200)),
                ('valor_plano', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
