# Generated by Django 6.0.4 on 2026-04-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=350)),
                ('idade', models.IntegerField()),
                ('faixa', models.CharField(choices=[('branca', 'Branca'), ('cinza', 'Cinza'), ('amarelo', 'Amarelo'), ('laranja', 'Laranja'), ('verde', 'Verde'), ('azul', 'Azul'), ('roxa', 'Roxa'), ('marrom', 'Marrom'), ('preta', 'Preta')], max_length=20)),
                ('graus', models.IntegerField(default=0)),
            ],
        ),
    ]
