# Generated by Django 6.0.4 on 2026-04-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='date_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
