# Generated by Django 6.0.4 on 2026-04-20 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_date_inicio'),
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='modalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inicio.modalidade'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inicio.plano'),
        ),
    ]
