# Generated by Django 6.0.4 on 2026-05-13 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_aluno_modalidade_aluno_plano'),
        ('modalidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='modalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modalidades.modalidade'),
        ),
    ]
