# Generated by Django 6.0.4 on 2026-05-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_alter_aluno_plano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='faixa',
            new_name='faixa_jiujitsu',
        ),
        migrations.AddField(
            model_name='aluno',
            name='faixa_judo',
            field=models.CharField(choices=[('branca', 'Branca'), ('cinza', 'Cinza'), ('amarelo', 'Amarelo'), ('laranja', 'Laranja'), ('verde', 'Verde'), ('azul', 'Azul'), ('roxa', 'Roxa'), ('marrom', 'Marrom'), ('preta', 'Preta')], default='branca', max_length=20),
            preserve_default=False,
        ),
    ]
