# Generated by Django 6.0.4 on 2026-05-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_rename_faixa_aluno_faixa_jiujitsu_aluno_faixa_judo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='faixa_jiujitsu',
            field=models.CharField(blank=True, choices=[('branca', 'Branca'), ('cinza', 'Cinza'), ('amarelo', 'Amarelo'), ('laranja', 'Laranja'), ('verde', 'Verde'), ('azul', 'Azul'), ('roxa', 'Roxa'), ('marrom', 'Marrom'), ('preta', 'Preta')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='faixa_judo',
            field=models.CharField(blank=True, choices=[('branca', 'Branca'), ('cinza', 'Cinza'), ('amarelo', 'Amarelo'), ('laranja', 'Laranja'), ('verde', 'Verde'), ('azul', 'Azul'), ('roxa', 'Roxa'), ('marrom', 'Marrom'), ('preta', 'Preta')], max_length=20, null=True),
        ),
    ]
