# Generated by Django 6.0.4 on 2026-05-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_alter_aluno_modalidade'),
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modalidade',
        ),
    ]
