# Generated by Django 6.0.4 on 2026-05-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_alter_aluno_plano'),
        ('inicio', '0002_delete_modalidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plano',
        ),
    ]
